### ISSUE TITLE
Cleanup and modernize configure.in and Makefiles

### ISSUE THREAD

**Issue by cosmos72** [cosmos72/twin#3]
Both configure.in and Makefiles contain a lot of ad-hoc rules, with varying degrees of bit-rot, to the point that I have not been able to regenerate the configure script since years... also, Makefiles do not use automake at all.

The whole build process depends on GNU make and bash, and is somewhat fragile.

Volunteers are welcome :)

**Comment by Mirppc** [comment]
Working on compiling TWIN for the CHIP.  The head of the local LUG was excited about the TWIN project, he is a better programmer than i am.  Hopefully i can bribe him to volunteer :P

**Comment by cosmos72** [comment]
Funny timing... I just completed this activity two days ago :)

**Comment by cosmos72** [comment]
I guess CHIP is some kind of system-on-chip or embedded platform... where can I find more information about it?
Due to the name, googling it is disaster...

**Comment by Mirppc** [comment]
here is a link to the documentation.  all the code is avalible here on github. http://docs.getchip.com/

https://getchip.com/

I was a kickstarter backer and chose one of those instead of a pi. 

 I also have an Odroid U2 (http://www.hardkernel.com/main/products/prdt_info.php?g_code=G135341370451)  with ubuntu installed that i could test, though i think i might have gotten twin successfully compiled.  

one thing i might do is edit the dependencies in the readme.  for a good tty session you need gpm ncurses ncurses-dev/ncurses-devel  whatever provides termcap.h and i think there was one other that i needed when compiling on the odroid.
